base_dir: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tool_workers
log_folder: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tool_workers/logs/server_log
partition: "MoE"
default_calculate_gpus: 1
default_calculate_cpus: 16
default_control_cpus: 2
default_control_gpus: 0
retry_interval: 1
request_timeout: 10

controller_config:
  worker_name: controller
  job_name: zc_controller
  calculate_type: control
  cmd:
    script-addr: controller.py
    port: 20001
    host: "0.0.0.0"

model_worker_config:
  - qwenvl:
      worker_name: qwenvl
      job_name: zc_qwenvl
      calculate_type: calculate
      cmd:
        script-addr: ../model_workers/qwen2vl_worker.py
        model-path: "/mnt/petrelfs/share_data/quxiaoye/models/Qwen2-VL-72B-Instruct" 
        model-name: Qwen2-VL-72B-Instruct
        port: 40001
        host: "0.0.0.0"

tool_worker_config:
  - grouding:
      calculate_type: calculate
      worker_name: grouding
      job_name: zc_grouding
      cmd:
        script-addr: ./grounding_dino_worker.py
        port: 20003
        host: "0.0.0.0"
        model-config: "/mnt/petrelfs/songmingyang/code/reasoning/tool-agent/LLaVA-Plus-Codebase/dependencies/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
        model-path: "/mnt/petrelfs/songmingyang/songmingyang/model/tool-augment/groundingdino/groundingdino_swint_ogc.pth"

  - ocr:
      worker_name: ocr
      job_name: zc_ocr
      calculate_type: control
      cmd:
        script-addr: ./ocr_worker.py
        port: 20009
        host: "0.0.0.0"
  - line:
      worker_name: line
      job_name: zc_line
      calculate_type: control
      cmd:
        script-addr: ./restructure_worker/drawline_worker.py
        port: 20011
        host: "0.0.0.0"
  - crop:
      worker_name: crop
      job_name: zc_crop
      calculate_type: control
      cmd:
        script-addr: "./restructure_worker/crop_worker.py"
        port: 20013
        host: "0.0.0.0"
  
