base_dir: /mnt/petrelfs/share_data/suzhaochen/new_tool/Tool-Factory/tool_server/tool_workers
log_folder: /mnt/petrelfs/share_data/suzhaochen/new_tool/Tool-Factory/tool_server/tool_workers/logs/server_log_15
partition: "MoE"
default_calculate_gpus: 0
default_calculate_cpus: 2
default_control_cpus: 2
default_control_gpus: 0
retry_interval: 1
request_timeout: 10

controller_config:
  worker_name: controller
  job_name: zc_controller
  calculate_type: control
  srun_kwargs:
    w: SH-IDCA1404-10-140-54-15
  cmd:
    script-addr: ./online_workers/controller.py
    port: 20001
    host: "0.0.0.0"


tool_worker_config:
  - Point:
      worker_name: Point
      job_name: zc_point
      calculate_type: calculate
      conda_env: "molmo"
      srun_kwargs:
        w: SH-IDCA1404-10-140-54-15
      cuda_visible_devices: "7"
      cmd:
        script-addr: ./online_workers/molmo_point_worker.py
        port: 20027
        host: "0.0.0.0"
        model_path: "/mnt/petrelfs/share_data/suzhaochen/models/Molmo-7B-D-0924"

  - SegmentRegionAroundPoint:
      worker_name: SegmentRegionAroundPoint
      job_name: zc_sam2
      calculate_type: calculate
      conda_env: "sam2"
      srun_kwargs:
        w: SH-IDCA1404-10-140-54-15
      cuda_visible_devices: "7"
      cmd:
        script-addr: ./online_workers/SAMAroundPoint_worker.py
        port: 20036
        host: "0.0.0.0"
        sam2_checkpoint: /mnt/petrelfs/share_data/suzhaochen/models/sam2-hiera-large/sam2_hiera_large.pt
        sam2_model_cfg: sam2_hiera_l.yaml

  - DrawHorizontalLineByY:
      worker_name: DrawHorizontalLineByY
      job_name: zc_drawliney
      calculate_type: control
      srun_kwargs:
        w: SH-IDCA1404-10-140-54-15
      cmd:
        script-addr: ./online_workers/DrawHorizontalLineByY_worker.py
        port: 20032
        host: "0.0.0.0"

  - DrawVerticalLineByX:
      worker_name: DrawVerticalLineByX
      job_name: zc_drawlinex
      calculate_type: control
      srun_kwargs:
        w: SH-IDCA1404-10-140-54-15
      cmd:
        script-addr: ./online_workers/DrawVerticalLineByX_worker.py
        port: 20089
        host: "0.0.0.0"

  - ZoomInSubfigure:
      worker_name: ZoomInSubfigure
      job_name: zc_SelectSubplot
      calculate_type: control
      srun_kwargs:
        w: SH-IDCA1404-10-140-54-15
      cmd:
        script-addr: ./online_workers/SelectSubplot_worker.py
        port: 20039
        host: "0.0.0.0"

  - OCR:
      worker_name: OCR
      job_name: zc_ocr
      calculate_type: control
      srun_kwargs:
        w: SH-IDCA1404-10-140-54-15
      cmd:
        script-addr: ./online_workers/ocr_worker.py
        port: 20009
        host: "0.0.0.0"
