task_name: "charxiv"
dataset_path: princeton-nlp/CharXiv
num_sample: 500
dataset_type: "unique" # Which means we need to implement load data logic sepretely for charxiv
generation_config:
  max_length: 2048

