model_args:
  model: llava_plus
  model_args: pretrained=/mnt/petrelfs/share_data/quxiaoye/models/llava_plus_v0_7b
  batch_size: 2
  max_rounds: 3
  stop_token: <stop>
task_args:
  task_name: charxiv
  resume_from_ckpt:
    charxiv: ./tool_server/tf_eval/scripts/logs/ckpt/charxiv/llava_plus.jsonl
  save_to_ckpt:
    charxiv: ./tool_server/tf_eval/scripts/logs/ckpt/charxiv/llava_plus.jsonl
script_args:
  verbosity: INFO
  output_path: ./tool_server/tf_eval/scripts/logs/results/charxiv/llava_plus.jsonl
  # controller_addr: http://10.140.54.30:20001